version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - '4200:4200'
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
